import { defineConfig } from 'windicss/helpers';
import aspectRatio from 'windicss/plugin/aspect-ratio';
import forms from 'windicss/plugin/forms';
import lineClamp from 'windicss/plugin/line-clamp';
import typography from 'windicss/plugin/typography';

export default defineConfig({
  attributify: true,
  darkMode: 'class',
  plugins: [aspectRatio, forms, lineClamp, typography],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--primary-400)',
          50: 'var(--primary-50)',
          100: 'var(--primary-100)',
          200: 'var(--primary-200)',
          300: 'var(--primary-300)',
          400: 'var(--primary-400)',
          500: 'var(--primary-500)',
          600: 'var(--primary-600)',
          700: 'var(--primary-700)',
          800: 'var(--primary-800)',
          900: 'var(--primary-900)',
        },
        secondary: {
          surface: 'var(--secondary-50)',
          lightest: 'var(--secondary-100)',
          lighter: 'var(--secondary-200)',
          light: 'var(--secondary-300)',
          DEFAULT: 'var(--secondary-400)',
          dark: 'var(--secondary-500)',
          darker: 'var(--secondary-600)',
          darkest: 'var(--secondary-700)',
          black: 'var(--secondary-800)',
        },
        tertiary: {
          DEFAULT: 'var(--tertiary-400)',
          50: 'var(--tertiary-50)',
          100: 'var(--tertiary-100)',
          200: 'var(--tertiary-200)',
          300: 'var(--tertiary-300)',
          400: 'var(--tertiary-400)',
          500: 'var(--tertiary-500)',
          600: 'var(--tertiary-600)',
          700: 'var(--tertiary-700)',
          800: 'var(--tertiary-800)',
          900: 'var(--tertiary-900)',
        },
        cloud: {
          surface: 'var(--cloud-50)',
          lightest: 'var(--cloud-100)',
          lighter: 'var(--cloud-200)',
          light: 'var(--cloud-300)',
          DEFAULT: 'var(--cloud-400)',
          dark: 'var(--cloud-500)',
          darker: 'var(--cloud-600)',
          darkest: 'var(--cloud-700)',
          black: 'var(--cloud-800)',
        },
      },
      borderColor: (theme) => ({
        ...theme('colors'),
      }),
      spacing: {
        base: '320px',
        header: 'var(--header-height)',
        18: '4.5rem',
      },
      height: (theme) => ({
        '(full-18)': `calc(100% - ${theme('spacing.18')})`,
        '(full-header)': `calc(100% - ${theme('spacing.header')})`,
        '(screen-18)': `calc(100vh - ${theme('spacing.18')})`,
        '(screen-header)': `calc(100vh - ${theme('spacing.header')})`,
      }),
      maxHeight: (theme) => ({
        '(screen-18)': `calc(100vh - ${theme('spacing.18')})`,
        '(screen-header)': `calc(100vh - ${theme('spacing.header')})`,
      }),
      minHeight: () => ({
        'fill-available': '-webkit-fill-available',
      }),
      maxWidth: {
        base: '320px',
        '8xl': '90rem',
        half: '50%',
      },
      minWidth: {
        half: '50%',
      },
      inset: {
        18: '4.5rem',
      },
    },
  },
  /* eslint-disable prettier/prettier */
  shortcuts: {
    'd-logo': 'w-auto h-6 md:h-7 text-logo dark:text-white',
    'd-body-bg': 'bg-white dark:bg-secondary-black',
    'd-body-text-color': 'text-secondary-darker dark:text-white',
    'd-secondary-bg': 'bg-gray-500 dark:bg-cloud-light',
    'd-secondary-text': 'text-gray-500 dark:text-cloud-light',
    'd-secondary-text-hover': 'text-gray-700 dark:text-cloud-lightest',
    'd-secondary-text-active': 'text-gray-900 dark:text-cloud-surface',
    'd-primary-text-hover': 'text-gray-600 dark:text-cloud-lighter',
    'd-prose-code-inline-bg': 'bg-gray-100 dark:bg-secondary-darkest',
    'd-prose-code-bg': 'bg-gray-100 dark:bg-secondary-darkest',
    'd-header-home': 'sticky w-full top-0 z-50 bg-secondary-black bg-opacity-80 d-border-header d-blur-header h-header',
    'd-bg-header': 'bg-white bg-opacity-80 dark:bg-secondary-black dark:bg-opacity-80',
    'd-bg-header-home': 'bg-opacity-80 bg-secondary-black',
    'd-border': 'light:border-gray-200 light:border-opacity-50 dark:border-secondary-darker',
    'd-border-hover': 'border-primary-200 dark:border-secondary-dark',
    'd-border-header': 'border-none',
    'd-page-mobile-toc-bg': 'd-body-bg bg-opacity-80 dark:bg-opacity-80',
    'd-aside-header-bg': 'bg-gray-50 dark:bg-secondary-darkest',
    'd-aside-header-home-bg': 'bg-secondary-darkest',
    'd-active-aside-navigation-item-bg': 'bg-primary-50 dark:bg-secondary-darkest',
    'd-active-aside-navigation-item-text': 'text-primary-500 dark:text-primary ',
    'd-code-group-header-bg': 'bg-gray-200 dark:bg-secondary-darker',
    'd-code-group-tab': 'bg-gray-300 dark:bg-secondary-dark',
    'd-prose-code-filename-bg': 'bg-gray-100 dark:bg-secondary-darker',
    'd-prose-code-filename-text': 'text-gray-600 dark:text-secondary-light',
    'd-prose-thead-border': 'border-b border-gray-200 dark:border-secondary-dark',
    'd-prose-tr-border': 'border-b border-gray-100 dark:border-secondary-darker',
    'd-prose-blockquote-border': 'border-l-2 border-gray-200 dark:border-secondary-darker',
    'd-tertiary-text': 'text-gray-400 dark:text-cloud-dark',
    'd-prose-hr-border': 'border-t border-gray-100 dark:border-secondary-darker',
    'd-prose-ul-li-bullet': 'd-secondary-bg',
    'd-scrollbar': 'scrollbar-thin scrollbar-thumb-gray-200 dark:scrollbar-thumb-secondary-dark scrollbar-thumb-rounded',
    'd-max-w-container': 'max-w-7xl',
    'd-px-container': 'px-4 sm:px-6',
    'd-container': 'd-max-w-container mx-auto',
    'd-container-content': 'd-container d-px-container',
    'd-blur-header': 'blur-12',
    'd-aside-title': 'py-2 text-base font-semibold text-gray-900 cursor-pointer dark:text-gray-100',
  },
});
